### ISSUE TITLE
Recompiler bug

### ISSUE THREAD

**Issue by D0nato16** [GreyDynamics/Frostbite3_Editor#3]
Hello,
when I edit two different ebx file in the same .sb file the editor save only the last edit.
for example: I edit ace23 and aek971, the tool recompile .sb files two times and only the last change was saved.

Sorry for my bad english

**Comment by GreyDynamics** [comment]
**The bug has been fixed in version 0.40A_pre2.
Thank you for contributing.**

Tested it for cas and noncas.
Initial direction from 0.2 to 2.2 for medicbag and c4:
https://www.youtube.com/watch?v=998JPWq_-y0

PS: I noticed a unhandled field while compiling the superbundle. This will be fixed soon.
This should not effect your current experience.

**Comment by D0nato16** [comment]
Thank You
